hmrc/pensions-scheme

- conf/application.conf
Reverts hmrc/pensions-scheme#44
> Revert "Remove max size from mongo collections"

- app/audit/PSARegistration.scala
- app/audit/PSASubscription.scala
- app/audit/SchemeList.scala
- app/audit/SchemeSubscription.scala
- app/connector/RegistrationConnector.scala
- app/service/SchemeServiceV1.scala
- test/audit/testdoubles/StubSuccessfulAuditService.scala
- test/connector/RegistrationConnectorSpec.scala
- test/service/SchemeServiceV1Spec.scala
PSASubscription
SchemeSubscription
SchemeList
> PODS-1087: Add payload to audit events

- app/bindings/FeatureBindings.scala
- app/models/PensionsScheme.scala
- app/models/ReadsEstablisherDetailsV2.scala
- app/service/SchemeServiceImpl.scala
- app/service/SchemeServiceV2.scala
- test/bindings/FeatureBindingsSpec.scala
- test/models/Reads/CustomerAndSchemeDetailsReadsSpec.scala
- test/models/Reads/establishersv2/EstablishersTestData.scala
- test/models/Reads/establishersv2/EstablishersTestJson.scala
- test/models/Reads/establishersv2/ReadsEstablisherDetailsV2Spec.scala
- test/service/SchemeServiceImplSpec.scala
- test/service/SchemeServiceV2Spec.scala
Tidy up
SchemeServiceV2
FeatureBindings
organization not organisation
> PODS-1054: JSON transform for multiple establishers

- conf/application.conf
Reverts hmrc/pensions-scheme#60
> Revert "Switching contact address to false to match prod"

- app/models/PensionSchemeAdministrator.scala
- test/models/Samples.scala
> Company name hot fix

- app/utils/ErrorHandler.scala
Reverts hmrc/pensions-scheme#75
> Revert "Pods 1245"

- app/controllers/EmailResponseController.scala
- test/controllers/EmailResponseControllerSpec.scala
Reverts hmrc/pensions-scheme#86
> Revert "Pods 1519: No auditing on opened events, only audit last of email events in collection"

- app/models/schemes/CompanyDetails.scala
- app/models/schemes/IndividualDetails.scala
- app/models/schemes/PreviousAddressDetails.scala
- test/models/Reads/AddressReadsSpec.scala
- test/models/Reads/behaviours/AddressReadsBehaviours.scala
- test/models/Reads/schemes/CompanyDetailsReadsSpec.scala
- test/models/Reads/schemes/IndividualsDetailsReadsSpec.scala
- test/models/Reads/schemes/MockData.scala
- test/models/Reads/schemes/MockSchemeData.scala
- test/models/Reads/schemes/PreviousAddressDetailsReadsSpec.scala
PODS-1684 : create models for companys
> PODS-1684 : create models for companys

- app/models/schemes/CompanyDetails.scala
- app/models/schemes/EstablisherInfo.scala
- app/models/schemes/IndividualInfo.scala
- app/models/schemes/PartnershipDetails.scala
- app/models/schemes/PsaSchemeDetails.scala
- app/models/schemes/TrusteeInfo.scala
- test/models/Reads/schemes/CompanyDetailsReadsSpec.scala
- test/models/Reads/schemes/EstablisherInfoReadsSpec.scala
- test/models/Reads/schemes/IndividualInfoReadsSpec.scala
- test/models/Reads/schemes/PartnershipDetailsReadsSpec.scala
- test/models/Reads/schemes/PsaSchemeDetailsReadsSpec.scala
- test/models/Reads/schemes/SchemeDetailsStubData.scala
- test/models/Reads/schemes/SchemeDetailsStubJsonData.scala
- test/models/Reads/schemes/TrusteeInfoReadsSpec.scala
PODS-1680 : Create model for Trustee Details in Pensions-Scheme
> PODS-1680 : Create model for Trustee Details in Pensions-Scheme

- app/connector/SchemeConnector.scala
- app/models/schemes/CompanyDetails.scala
- app/models/schemes/IndividualInfo.scala
- app/models/schemes/PartnershipDetails.scala
- app/models/schemes/PsaSchemeDetails.scala
- conf/resources/schemas/schemeDetailsReponse.json
- test/models/Reads/schemes/CompanyDetailsReadsSpec.scala
- test/models/Reads/schemes/IndividualInfoReadsSpec.scala
- test/models/Reads/schemes/PartnershipDetailsReadsSpec.scala
- test/models/Reads/schemes/PsaSchemeDetailsReadsSpec.scala
- test/models/Reads/schemes/SchemeDetailsStubData.scala
- test/models/Reads/schemes/SchemeDetailsStubJsonData.scala
PODS-1680 : model updated with correct establisher and trustee type and reads for address
> PODS-1680 : model updated with correct establisher and trustee type and reads for address

- app/models/schemes/PsaSchemeDetails.scala
- project/MicroServiceBuild.scala
- test/models/Reads/schemes/CompanyDetailsReadsSpec.scala
- test/models/Reads/schemes/EstablisherInfoReadsSpec.scala
- test/models/Reads/schemes/IndividualInfoReadsSpec.scala
- test/models/Reads/schemes/IndividualsDetailsReadsSpec.scala
- test/models/Reads/schemes/PSASchemeDetailsGenerator.scala
- test/models/Reads/schemes/PartnershipDetailsReadsSpec.scala
- test/models/Reads/schemes/PreviousAddressInfoReadsSpec.scala
- test/models/Reads/schemes/PsaDetailsReadsSpec.scala
- test/models/Reads/schemes/PsaSchemeDetailsReadsSpec.scala
- test/models/Reads/schemes/SchemeDetailsReadsSpec.scala
- test/models/Reads/schemes/TrusteeInfoReadsSpec.scala
PODS-1726 : Add property based testing for PSA scheme details Json data
> PODS-1726 : Add property based testing for PSA scheme details Json data

- conf/application.conf
Reverts hmrc/pensions-scheme#120
> Revert "PODS-1748 Correct endpoint"

- app/models/PensionsScheme.scala
- app/service/SchemeServiceImpl.scala
- app/utils/Toggles.scala
- conf/application.conf
- test/config/FeatureSwitchManagementServiceSpec.scala
- test/models/Reads/CustomerAndSchemeDetailsReadsSpec.scala
- test/models/Reads/PensionSchemeDeclarationReadsSpec.scala
- test/service/SchemeServiceImplSpec.scala
- test/service/SchemeServiceSpec.scala
PODS-2252: removed the enable-hub-v2 toggle
>  PODS-2252: removed the enable-hub-v2 toggle

- test/utils/SchemaValidatorForTests.scala
> write fix for address

- conf/resources/schemas/schemeSubscription.json
> subscription scheme updated

- app/models/PensionsScheme.scala
- test/models/Reads/schemes/PSASchemeDetailsGenerator.scala
- test/models/Writes/CustomerAndSchemeDetailsWriteSpec.scala
- test/utils/PensionSchemeGenerators.scala
PODS-2284 : Scheme variances - CustomerAndSchemeDetails - [JSON Writes to API1468]
> PODS-2284 : Scheme variances - CustomerAndSchemeDetails - [JSON Writes to API1468] 

- app/models/PensionsScheme.scala
- test/models/Writes/PensionSchemeDeclarationWriteSpec.scala
- test/service/SchemeServiceSpec.scala
PODS-2285 : Scheme variances - PensionSchemeDeclaration - [JSON Writes to API1468]
> PODS-2285 : Scheme variances - PensionSchemeDeclaration - [JSON Writes to API1468]

- app/models/jsonTransformations/EstablisherDetailsTransformer.scala
- app/models/jsonTransformations/JsonTransformer.scala
- app/models/jsonTransformations/TrusteeDetailsTransformer.scala
- test/models/Transformers/EstablisherDetailsTransformerSpec.scala
- test/models/Transformers/TrusteeDetailsTransformerSpec.scala
- test/utils/PensionSchemeJsValueGenerators.scala
PODS-2279 : Scheme variances - TrusteeDetails - [Get Scheme Details to UserAnswers JSON Transformation]
> PODS-2279 : Scheme variances - TrusteeDetails - [Get Scheme Details to UserAnswers JSON Transformation]

- app/controllers/SchemeController.scala
- app/models/PensionsScheme.scala
- app/service/SchemeService.scala
- app/service/SchemeServiceImpl.scala
- project/AppDependencies.scala
- test/controllers/SchemeControllerSpec.scala
- test/models/Writes/EstablisherAndTrusteeTypeWritesSpec.scala
- test/models/Writes/EstablisherDetailsWritesSpec.scala
- test/models/Writes/PensionSchemeDeclarationWriteSpec.scala
- test/models/Writes/SchemeVariationDetailsWritesSpec.scala
- test/models/Writes/TrusteeDetailsWritesSpec.scala
- test/service/SchemeServiceImplSpec.scala
- test/service/SchemeServiceSpec.scala
- test/utils/PensionSchemeGenerators.scala
- test/utils/SchemaValidatorForTests.scala
PODS-2296 : Scheme variances - Wrapper Pensions Scheme Object - [JSON Writes to API1468]
> PODS-2296 : Scheme variances - Wrapper Pensions Scheme Object - [JSON Writes to API1468]

- app/repositories/CollectionDiagnostics.scala
logger added to do the analysis for row count in old pensions-scheme-psa-journey-scheme collection
> Pods 2254 analysis

- app/repositories/CollectionDiagnostics.scala
PODS-2254: feature resolved for row count
> PODS-2254: feature resolved for row count

- app/audit/SchemeAuditService.scala
- app/connector/SchemeConnector.scala
- app/controllers/AssociatedPsaController.scala
- app/controllers/SchemeDetailsController.scala
- app/models/Address.scala
- app/models/jsonTransformations/SchemeDetailsTransformer.scala
- test/connector/SchemeConnectorSpec.scala
- test/controllers/AssociatedPsaControllerSpec.scala
- test/controllers/SchemeDetailsControllerSpec.scala
- test/models/Reads/schemes/SchemeDetailsStubJsonData.scala
- test/resources/data/validGetSchemeDetailsUserAnswers.json
- test/service/SchemeServiceImplSpec.scala
- test/utils/FakeFeatureSwitchManagementService.scala
- test/utils/PensionSchemeJsValueGenerators.scala
PODS-2360 : Scheme Variances - Fix the connector in pensions-scheme to send the transformed user answers data for get scheme details
> PODS-2360 : Scheme Variances - Fix the connector in pensions-scheme to send the transformed user answers data for get scheme details

- test/models/Writes/EstablisherAndTrusteeTypeWritesSpec.scala
- test/models/Writes/SchemeVariationDetailsWritesSpec.scala
- test/utils/PensionSchemeGenerators.scala
PODS-2529: Random failures for pensions-scheme unit tests
> PODS-2529: Random failures for pensions-scheme unit tests

- app/controllers/SchemeVarianceLockCacheController.scala
- app/models/SchemeVarianceLockModel.scala
- app/repositories/LockRepository.scala
- conf/app.routes
- test/controllers/SchemeVarianceLockCacheControllerSpec.scala
- test/repositories/LockMongoRepositoryTest.scala
PODS-2516 : Scheme Variations - hide add/delete/change  links for schemes locked by another PSA
> PODS-2516 : Scheme Variations - hide add/delete/change  links for schemes locked by another PSA

- app/models/jsonTransformations/SchemeDetailsTransformer.scala
- test/resources/data/validGetSchemeDetailsUserAnswers.json
- test/utils/PensionSchemeJsValueGenerators.scala
PODS-2660: Scheme Variations - Insurance address not returned
> PODS-2660: Scheme Variations - Insurance address not returned

- app/models/PensionsScheme.scala
- app/service/SchemeServiceImpl.scala
- conf/resources/schemas/schemeVariationSchema.json
- test/models/Writes/IndividualWritesSpec.scala
- test/resources/schemas/api1468_schema.json
- test/service/SchemeServiceSpec.scala
PODS-2451 : API updated for scheme variance
> PODS-2451 : API updated for scheme variance 

- test/resources/data/validGetSchemeDetailsResponse.json
> PODS-2491: test fix

- app/models/jsonTransformations/EstablisherDetailsTransformer.scala
- app/models/jsonTransformations/JsonTransformer.scala
- test/resources/data/validGetSchemeDetailsUserAnswers.json
- test/resources/data/validGetSchemeDetailsUserAnswersToggleOff.json
- test/utils/PensionSchemeJsValueGenerators.scala
> Pods 3056 - Remove completion flags for establisher company

- app/models/etmpToUserAnswers/SchemeDetailsTransformer.scala
- app/models/etmpToUserAnswers/pspSchemeDetails/SchemeDetailsTransformer.scala
- app/models/userAnswersToEtmp/CustomerAndSchemeDetails.scala
- test/utils/PensionSchemeGenerators.scala
Reverts hmrc/pensions-scheme#278
> Revert "Pods 5354"

- app/models/etmpToUserAnswers/SchemeDetailsTransformer.scala
- app/models/etmpToUserAnswers/pspSchemeDetails/SchemeDetailsTransformer.scala
- app/models/userAnswersToEtmp/CustomerAndSchemeDetails.scala
- test/utils/PensionSchemeGenerators.scala
Reverts hmrc/pensions-scheme#279
> Revert "Revert "Pods 5354""
